export default {
  Registration: {
    BadUsername: 'BadUsername',
    BadEmail: 'BadEmail',
    BadPassword: 'BadPassword',
    UsernameTaken: 'UsernameTaken',
    EmailTaken: 'EmailTaken',
  },
  Login: {
    MissingToken: 'MissingToken',
    MissingAuth: 'MissingAuth',
    BadAuthType: 'BadAuthType',
    BadToken: 'BadToken',
    UsernameNotFound: 'UsernameNotFound',
    InvalidPassword: 'InvalidPassword',
    AccountNotFound: 'AccountNotFound',
    UserIsDeleted: 'UserIsDeleted',
  },
  Room: {
    MissingRoomId: 'MissingRoomId',
    MissingPostId: 'MissingPostId',
    BadOtherUsers: 'BadOtherUsers',
    BadRoomName: 'BadRoomName',
    RoomNotFound: 'RoomNotFound',
    NotInRoom: 'NotInRoom',
    BadPostContent: 'BadPostContent',
  },
  BadId: 'BadId',
  RouteNotFound: 'RouteNotFound',
  InternalError: 'InternalError',
};
